# Generated by Django 4.2.7 on 2024-08-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homework_description_alter_homework_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due',
            new_name='due_date',
        ),
    ]
