# Generated by Django 4.2.7 on 2023-11-21 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.FileField(upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub'])])),
            ],
        ),
    ]
